# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 22 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get weather forecast'
        run: bash ./weather.sh
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          serveraddress: smtp-mail.outlook.com
          serverport: 587
          username: ${{ secrets.EMAIL_ACCOUNT }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: 天气信息
          body: file://result.html
          to: ${{ secrets.EMAIL_TARGET }}
          from: GitHub Actions
          content_type: text/html
