# This is a basic workflow to help you get started with Actions

name: weather1

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 22 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get weather forecast'
        run: bash ./weather.sh
      - name: 'Send mail'
        uses: devellany/send-mail@v1.0.2
        with:
          host: smtp-mail.outlook.com
          port: 587
          account: ${{ secrets.EMAIL_ACCOUNT }}
          password: ${{ secrets.EMAIL_PASS }}
          sender: LSMCreativeWay
          from: ${{ secrets.EMAIL_ACCOUNT }}
          to: ${{ secrets.EMAIL_TARGET }}
          subject: 天气
          body: "test"
          contentType: text/html
